In [1]:
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant([1,2,3])

In [ ]:
dir(a)

In [5]:
from scipy import stats

In [6]:
dir(stats)

['BootstrapMethod',
 'CensoredData',
 'ConstantInputWarning',
 'Covariance',
 'DegenerateDataWarning',
 'FitError',
 'MonteCarloMethod',
 'NearConstantInputWarning',
 'PermutationMethod',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_axis_nan_policy',
 '_biasedurn',
 '_binned_statistic',
 '_binomtest',
 '_boost',
 '_censored_data',
 '_common',
 '_constants',
 '_continuous_distns',
 '_covariance',
 '_crosstab',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_entropy',
 '_fit',
 '_hypotests',
 '_kde',
 '_ksstats',
 '_levy_stable',
 '_mannwhitneyu',
 '_morestats',
 '_mstats_basic',
 '_mstats_extras',
 '_multicomp',
 '_multivariate',
 '_mvn',
 '_odds_ratio',
 '_page_trend_test',
 '_qmc',
 '_qmc_cy',
 '_qmvnt',
 '_rcont',
 '_relative_risk',
 '_resampling',
 '_rvs_sampling',
 '_sensitivity_analysis',
 '_sobol',
 '_statlib',
 '_stats',
 '_stats_mstats_common',
 '_stats_py',
 '_s

In [7]:
a = np.arange(24)

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
b = a.reshape(2,3,4)

In [13]:
b[0][0][0] = 1000

In [14]:
a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [15]:
np.reshape(a, (2,3,4))

array([[[1000,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [19]:
a.reshape(3,-3)

array([[1000,    1,    2,    3,    4,    5,    6,    7],
       [   8,    9,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23]])

In [ ]:
a.reshape

In [21]:
a = np.arange(24)

In [22]:
a.resize((3,6))

In [23]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [26]:
a.resize((3,10), refcheck=False)

In [27]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [28]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [29]:
b = a.flatten()

In [30]:
b[0] = 100

In [31]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [32]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [33]:
b = a.ravel()

In [34]:
b[0] = 100

In [35]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [36]:
aa = np.arange(6).reshape(2,3)

In [37]:
aa

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
aa[None]    # 2,3 -> 1,2,3

array([[[0, 1, 2],
        [3, 4, 5]]])

In [41]:
aa[...,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [42]:
aa[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [43]:
from collections import namedtuple

In [45]:
Point = namedtuple('Point', ['x', 'y'])

In [46]:
p1 = Point(x=3, y=4)

In [48]:
p1.x

3

In [49]:
p1[0]

3

In [50]:
import sys

In [51]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [52]:
# reshape
# - flatten - copy 기법
# - ravel - view 기법
# - [None] - 차원 증가

In [53]:
x = np.array([('Rex', 9, 81.0), ('Fibo', 3, 27.0)], 
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [54]:
# 이때, x가 structured array라고 한다
x[0]

('Rex', 9, 81.)

In [56]:
x['name']

array(['Rex', 'Fibo'], dtype='<U10')

In [59]:
xx = np.rec.array([('Rex', 9, 81.0), ('Fibo', 3, 27.0)], 
                  dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [61]:
xx.name

array(['Rex', 'Fibo'], dtype='<U10')

In [62]:
xxx = np.ma.array([1,2,3])

In [63]:
xxx

masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=999999)

In [64]:
xxx = np.ma.array([1,2,3], mask=[True, False, True])

In [65]:
xxx

masked_array(data=[--, 2, --],
             mask=[ True, False,  True],
       fill_value=999999)

In [66]:
xxx = np.matrix([[1,2], [3,4]])
# = xxx = np.mat([1,2], [3,4])

In [67]:
xxx
# repr이 array가 아니라 matrix 이다

matrix([[1, 2],
        [3, 4]])

In [68]:
# matrix에서 *은 matrix의 곱셈으로 작동된다

In [69]:
# functional programming
# reduce는 여러가지 값을 하나의 값으로 나타내주는 함수
# mean과 같은 아이들을 의미함
from functools import reduce

In [70]:
reduce(lambda x,y: x+y, [1,2,3,4,5])

15

In [71]:
a = np.arange(6).reshape(2,3)

In [72]:
a.strides
# 여기서 12는 0에서 3으로 내려가는데 12만큼 뒤에 있다는 뜻이다
# elements들은 메모리에 한 줄로 저장되어 있으며
# 속도가 매우 빠르다

(12, 4)

In [73]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
a.sum()

15

In [76]:
a.sum(axis = 0)
# axis에 따라 값을 모두 더해준다
# axis의 개념은 차원축소이다
# axis=0 0의 차원을 축소한다
# 여기서는 합으로 축소한다는 뜻이다

array([3, 5, 7])

In [77]:
aa = np.arange(24).reshape(2,3,4)

In [78]:
aa

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
aa.sum(axis=None)
# 전체 합

276

In [81]:
aa.sum(axis=1)  # size (2,3,4)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [82]:
aa.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [88]:
a = np.arange(6)

In [89]:
a

array([0, 1, 2, 3, 4, 5])

In [90]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
a.reshape(2,3, order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [92]:
a.reshape((2,3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
# 데이터 종류
# 파일 형식 : csv, excel ...
# databae : 데이터 베이스에서 불러오기
# 이미 저장된 상태에서 불러옴

# 파일 형식의 특색
# 분석 프레임워크 형태로 바꿔서 처리할 것이다
# 1. 파일 불러오기
#    text파일만 파이썬에서 불러올 수 있다
#    사람이 읽을 수 있는 형태 / 바이트 형태 두가지 존재
#    

In [96]:
a = open('./test.txt')

In [97]:
a.readline()

'asd\n'

In [ ]:
next(a)
# readline = next 서로 같다
# readline은 stop iteration 예외 처리가 존재한다
# next는 stopiteration 예외가 존재하지 않는다

# context 열어서 닫을 떄 까지
# 이 사이에 사용하는 것이 with이다

# text 파일은 별다른 기능 없이 모든 애들이 공통된 text로 저장한 것이다
# 

In [104]:
a.close()

In [131]:
class D:
    def __enter__(self):
        print("enter")
    def __exit__(self, a, b, c):
        # print(a, b, c)
        print("exit")
        print(a, b, c)

In [132]:
d = D()

In [133]:
with d:
    pass

enter
exit
None None None


In [139]:
import pickle

a = [1,2,3]

with open('b.txt', 'wb') as f:
    pickle.dump(a, f)
    # a must be str, not list
    # 확장자와 상관이 없다
    # list 저장 불가능이지만 pickle을 사용하여
    # 객체를 저장할 수 있다

In [140]:
with open('b.txt', 'rb') as f:
    xx = pickle.load(f)

In [141]:
xx

[1, 2, 3]

In [142]:
%%writefile c.txt
1 2 3
4 5 6

Writing c.txt


In [144]:
c = np.loadtxt('c.txt')
# string을 numpy 형식으로불러온다

In [145]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [149]:
np.save('c.npy',c)

In [151]:
np.load('c.npy')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [152]:
import inspect

In [154]:
print(inspect.getsource(tf.keras.datasets.mnist.load_data))

@keras_export("keras.datasets.mnist.load_data")
def load_data(path="mnist.npz"):
    """Loads the MNIST dataset.

    This is a dataset of 60,000 28x28 grayscale images of the 10 digits,
    along with a test set of 10,000 images.
    More info can be found at the
    [MNIST homepage](http://yann.lecun.com/exdb/mnist/).

    Args:
      path: path where to cache the dataset locally
        (relative to `~/.keras/datasets`).

    Returns:
      Tuple of NumPy arrays: `(x_train, y_train), (x_test, y_test)`.

    **x_train**: uint8 NumPy array of grayscale image data with shapes
      `(60000, 28, 28)`, containing the training data. Pixel values range
      from 0 to 255.

    **y_train**: uint8 NumPy array of digit labels (integers in range 0-9)
      with shape `(60000,)` for the training data.

    **x_test**: uint8 NumPy array of grayscale image data with shapes
      (10000, 28, 28), containing the test data. Pixel values range
      from 0 to 255.

    **y_test**: uint8 NumPy array 

In [ ]:
np.savez('c.npy', c)
# 따라서, 오래동안 보관 혹은 
# 영구적으로 보관해야할 경우에는
# pickle을 사용해야 한다