In [29]:
# imputer
import seaborn as sns
import numpy as np

In [3]:
from sklearn.datasets import fetch_openml
# make - random dataset 만들어줌
# load_ - 용량이 작은 dataset

In [2]:
titanic = sns.load_dataset('titanic')

In [7]:
titanic_sk = fetch_openml('titanic', version=1)

c:\Users\SAMSUNG\anaconda3\envs\KoreaUniv\lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [11]:
# 1st - check tidy data
# 2nd - info / missing data check, type check (문자열 데이터는 숫자로 바꿔야함, 문자열 들어가면 안됨)
# * 데이터가 더 많은 경우도 확인해야함
titanic.columns[titanic.isna().any()]
# 3rd - missing data count
titanic.age.isna().sum()
# 이때 sum에 skipna는 missing data 무시하고 count
# 

177

In [14]:
import missingno as mino

In [28]:
# mino.matrix(titanic)
# imputer - 가짜 데이터 삽입
# 특정 row를 지울 때도 있다
# 값을 채울때는? 평균, 최빈값, 중앙값
# 또는 KNN으로 가장 비슷한 애
# 또는 위치와 비슷한 애들의 평균값 등으로 넣어버림

# 1. 지운다
t = titanic.drop('deck', axis = 1)
# titanic[titanic.embarked.isna()].fillna(0)

# 2. 채운다
titanic[titanic.embarked.isna()].embarked.fillna(0)
# 동시에 값 넣어주기
titanic[titanic.embarked.isna()].embarked.fillna({61:0, 829:3})
# dict로 동시에 값 넣기 가능하다
# method로 채우기 가능
# bfill or pad 등
titanic.loc[58:63].embarked.fillna(method='bfill')

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_73484\3716101454.py:18: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  titanic.loc[58:63].embarked.fillna(method='bfill')


58    S
59    S
60    C
61    S
62    S
63    S
Name: embarked, dtype: object

In [30]:
titanic.loc[58:63].embarked.map(lambda x: 0 if x==np.nan else x)
# lambda 에서는 Nan을 절대 찾지 못함
# 왜? numpy masked array에서 missing data 처리하는데
# 이때 Nan 제외하고 연산해주기 때문이다
# 그래서 map을 하지 않는다

58      S
59      S
60      C
61    NaN
62      S
63      S
Name: embarked, dtype: object

In [40]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
# iterative는 아직 실험버전이니깐..

In [32]:
si = SimpleImputer()    # 1st instance / put option missing value 

In [ ]:
# scikit learn impute

# si.fit(titanic.age.values.reshape(1,-1))    # 2차원 넣어야하는데 numpy로 바꿔줘야함
# 하지만 fancy indexing을 사용함으로써 사용 가능
si.fit(titanic[['age']])
si.transform(titanic[['age']])
# transform으로 missing data를 바꿀 수 있다
# 이때 default 값으로 바뀌는데 strategy에 이미 존재하므로 바꿔서 값을 다르게 줄 수 있다
# 위의 두개를 한번에..
si.fit_transform(titanic[['age']])

In [38]:
# 다른 imputer
k = KNNImputer()    # 1st instance

In [ ]:
k.fit_transform(titanic[['age']])

In [41]:
import pandas as pd

In [43]:
pd.NA   # pandas에서 not available
# 얘로도 map은 안된다 그냥 사용하지마

<NA>

In [44]:
# impute는 진짜 같은 애를 넣기 위해서 분석을 통해서
# 특정 값 집어넣는 경우가 많다

In [45]:
# encoder
tips = sns.load_dataset('tips')
tips.dtypes # category data

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [46]:
tips.sex.map({'Male':0, 'Female':1})

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Name: sex, Length: 244, dtype: category
Categories (2, int64): [0, 1]

In [47]:
tips.sex.cat.codes
# code로 관리하는게 가능하다

0      1
1      0
2      0
3      0
4      1
      ..
239    0
240    1
241    0
242    0
243    1
Length: 244, dtype: int8

In [53]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [49]:
le = LabelEncoder()

In [50]:
le.fit_transform(tips.sex)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [51]:
# 장점: inverse_transform 지원
le.inverse_transform([0])
# 숫자 0이 무엇인지 알려준다
# 거꾸로 바꿔주는 것

array(['Female'], dtype=object)

In [52]:
iris = sns.load_dataset('iris')
iris
# 문자열, 

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [54]:
oe = OrdinalEncoder()

In [ ]:
oe.fit_transform(tips[['sex']])
# 정확한 값을 찾아내기 귀찮다
# 따라서 나온게 one hot encoder

In [57]:
# one hot

tips.sex.str.get_dummies()

Female  Male
0         1     0
1         0     1
2         0     1
3         0     1
4         1     0
..      ...   ...
239       0     1
240       1     0
241       0     1
242       0     1
243       1     0

[244 rows x 2 columns]

In [58]:
tips.day.str.get_dummies()
# 서로 비교시에 크기의 값이 없어진다
# 단점: column이 늘어난다

Fri  Sat  Sun  Thur
0      0    0    1     0
1      0    0    1     0
2      0    0    1     0
3      0    0    1     0
4      0    0    1     0
..   ...  ...  ...   ...
239    0    1    0     0
240    0    1    0     0
241    0    1    0     0
242    0    1    0     0
243    0    0    0     1

[244 rows x 4 columns]

In [59]:
# multi hot
# 아래로 긴 위로 긴 원 사각형

In [60]:
# One hot encoder
from sklearn.preprocessing import OneHotEncoder

In [62]:
one = OneHotEncoder()
one.fit_transform(tips[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [63]:
one.inverse_transform([[0,1]])

array([['Male']], dtype=object)

In [64]:
from sklearn.datasets import load_iris

In [65]:
data = load_iris(as_frame=True)
iris = data.frame
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(iris.iloc[:,:-1], iris.target)

GaussianNB()

In [66]:
gb.predict([[1,2,3,2], [3,3,3,4]])
# 예측을 2d로도 가능하다

c:\Users\SAMSUNG\anaconda3\envs\KoreaUniv\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([2, 2])

In [67]:
# 데이터 쪼개기
# training, testing dataset으로 쪼갬

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(iris.iloc[:,:-1], iris.target)

In [70]:
gb.fit(X_train, y_train)

GaussianNB()

In [73]:
# 검증 하는 방법
(gb.predict(X_test) == y_test).sum()
# 원래 38개 중에 36개 맞춘 것

36

In [74]:
# train과 test로 분리하는 것을 holdout이라고 한다

In [ ]:
# 모델 선택
# trade off 두개 못가짐 따라서 둘 중 하나를 선택해야만 한다

In [ ]:
# 내가 만든 모델은 현실세계를 단순화한 것
# 가정을 해야함 따라서,
# 