In [1]:
# representation learning
# CNN

# deep learning book
# 거의 바이블인데 기본서다

# representation learning
# 데이터를 다른 형태로 변환 (목적에 맞는 데이터 형태)
# 어떻게 표현하는가에 따라서 머신러닝 성능이 달라지기 때문이다
# 하지만, dll은 표현하는 것을 학습을 통해서 하는 것
# 따라서, 표현 방법에 따라서 성능이 달라졌다면
# 이제는 데이터를 기준으로 성능이 달라지기 않는다
# 그래서 성능이 좋을 수 밖에 없다

# 따라서, dll의 핵심은 representation
# 레이어를 통과하면서 데이터 형태가 바뀌는데
# 마지막에 우리가 원하는 데이터 형태로 나온다
# representation으로 linear한 형태로 바뀌게 된다
# 이때, 문제가 존재
# 이미지의 경우,
# 1. 차원의 저주 문제 -> 데이터가 많으면 해결가능함
# 2. 공간적인 의미가 사라짐 (flatten했을 때) 따라서 한계가 존재함 (로컬 정보를 잃어버린다)
# 그래서 입력을 2차 이상으로 받는 것으로 해결

# 뉴럴 네트워크의 문제점
# 1. 고양이의 위치가 바뀔 수록 고양이 인식을 못함
# 2. 사람은 고양이의 눈, 코, 입 등의 특성으로 인식하는데 이를 수행하지 못함

# 특성이 있는지 없는지의 문제로 바꾼다 (신호의)
# 이미지는 독립적이지 않으므로 머신러닝에서 문제가 생길 수 있다
# ex. welcome 일때 w,e,l,..이 나왔는데 순서대로 나오지 않을 수 있으므로 존재 유무 차이로 하면 문제가 존재했다
# 그래서 welcome의 위치를 보고 위치 확인함
# 하지만 feature 존재로 확인할 경우에서 문제가 존재함
# 이를 해결하기 위해서 window size의 다양성으로 해결할 수 있다
# fc에서는 위치와 크기에 따라서 task가 해결이 안되는문제
# 이를 해결하려고 window의 위치와 크기의 다양성으로 독립성 가정 문제가 해결됨

# equivalance = 이동을 해도 특성이 사라지지 않으므로 특성이 같으면 equivalance라고 한다 (즉, 이동 말고 바뀐게 없을 때)
# invariance = 이동해도 안변하는 것을 특성이 변하지 않는 것
# convolution = translation equivalance의 종류 (이동을 해도 똑같은 것을 인식하는 애)
# 따라서, 데이터의 양이 확 줄어들 수 있다 (성능을 높이는데 사용)

# 이미지를 쪼갬 (window를 이동시키는 것이 아님)
# 이 쪼갠 이미지를 보면서 결과값이 있는지 없는지 보는 것
# 이것이 convolution - 새로운 데이터 형식의 연산

# convolution - 면적의 넓이를 함수로 나타냄 (불연속을때는 내적처리)

In [2]:
from scipy import signal

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([-2,0,1])

In [5]:
# correlation

In [6]:
signal.correlate(a,b)

array([  1,   2,   1,   0,  -1,  -8, -10])

In [7]:
# correlation 연산
# a를 padding함
# 두 패턴이 비슷하면 비슷할수록 값이 크다
# pattern의 존재 유무를 알 수 있다
# 하지만 교환법칙이 성립되지 않아서 convolution이 나옴
# correlate(b, a)

In [8]:
# conbolution = flip + correlation
a

array([1, 2, 3, 4, 5])

In [9]:
b

array([-2,  0,  1])

In [10]:
np.flip(b)

array([ 1,  0, -2])

In [11]:
signal.correlate(a,b)

array([  1,   2,   1,   0,  -1,  -8, -10])

In [13]:
signal.correlate(np.flip(b), a)

array([ 5,  4, -7, -6, -5, -4, -2])

In [14]:
signal.correlate(a, np.flip(b))

array([-2, -4, -5, -6, -7,  4,  5])

In [15]:
signal.correlate(b, np.flip(a))

array([-2, -4, -5, -6, -7,  4,  5])

In [16]:
# convolution은 교환법칙이 적용되므로 correlation 연산을 한다
# 그래서 왜? convolution ? 수학적으로 증빙하기 위해서
# 특성의 있고 없고의 여부를 따질 때, 교한 법칙 시에 값이 동일하므로 존재 여부 따지기가 좋다
# convolution의 다른 특성: 내적 연산
# 이미지 처리에서는 filter로 쓰인다

In [ ]:
# 재정리
# ML에서의 이미지 처리는
# 1. 1차 형태의 데이터로 바꿔야한다 - 문제: 차원의 저주, 로컬 정보 손실
# Neural Network의 문제점 - FC이므로 크기와 위치 회전 등 다르면 다 다르다고 인식을 한다
# 따라서, 해결하기 위해서
# 1. 2,3 차 형태로 input data를 구성한다 (1차로 변환시킬 때 문제)
# 2. 위의 문제점을 특성이 있는지 없는지의 형태로 변환 - 정보의 손실이 적고, 독립성 과정도 가능하다, 로컬 정보 활용 가능하다

# ---- correlation ---- > 로컬 정보 활용 - 로컬 정보 손실 해결
# 1차로 변환 시, 문제 소지 감소, 독립성 가정 확보
# 하지만 correlation은 교환법칙이 성립을 못하므로 증명이 힘듦
# 그래서 convolution = correlation + flip
# 이를 통해 위치의 문제가 상관이 없어진다
# 이러면 neural network의 연산 특징과 유사하다
# 이때, flip은 교환법칙 성립을 위해서...
# 하지만 하나의 특징으로 모든 것을 해결 못하는 문제가 생김

# 따라서 이것을 여러개 사용하면 여러 특징을 볼 수 있다

# 이미지 > 이미지 (image processing) : filter (convolution을 filter로 활용함)
# cnn explainer

# CNN (input = 2, 3 dimension why? 정보 손실이 작아지므로)
# convolution2D layer
# flatten layer
# FC