In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = a

In [4]:
b[0] = 100

In [5]:
a

array([100,   2,   3])

In [6]:
a = np.array([1,2,3])

In [7]:
b = a.copy()

In [13]:
x = [[1,2],[3,4]]

In [9]:
y = x.copy()

In [10]:
y[0][0] = 100

In [11]:
x

[[100, 2], [3, 4]]

In [12]:
import copy

In [14]:
y = copy.deepcopy(x)

In [15]:
y[0][0] = 100

In [16]:
x

[[1, 2], [3, 4]]

In [17]:
xx = np.array([[1,2],[3,4]])

In [18]:
yy = xx.copy()

In [19]:
yy[0,0] = 100

In [20]:
xx

array([[1, 2],
       [3, 4]])

In [21]:
a = np.arange(24).reshape(4,6)

In [22]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
a[1][:]
#python 방식
# or
a[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [25]:
a[[1]]
# fancy indexing

array([[ 6,  7,  8,  9, 10, 11]])

In [26]:
a[[2,1]]
# 재조합 가능

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

In [27]:
b = a[[1]]
b[0,1] = 100
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
a[[0,2],[1,1]]

array([ 1, 13])

In [32]:
a[(0,1),(2,1)]

array([2, 7])

In [33]:
a[(0,1,-1), (2,1,-3)]

array([ 2,  7, 21])

In [36]:
a[1,1]

7

In [44]:
a[[0,2],[0,1]]

array([ 0, 13])

In [46]:
a[None]

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [47]:
aa = np.arange(24).reshape(2,3,4)

In [51]:
aa

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
aa[:,:,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [58]:
aa[:,1,:]
# ==>

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [59]:
aa[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [62]:
# scipy > ndimage > scipy-toolkit
#       > ml      > scikit-learn

array([[ 1,  5,  9],
       [13, 17, 21]])