In [3]:
import pickle
import pandas as pd

In [4]:
data = pd.read_pickle('../19th day/reco')

In [ ]:
data

In [6]:
def sim(user_id, n=5):
    return data[user_id].sort_values(ascending=False)[1:n+1]

In [7]:
data.loc[1].nlargest(5)

UserID
1       1.000000
5343    0.405356
5190    0.404446
1481    0.380623
1283    0.379054
Name: 1, dtype: float64

In [8]:
data.loc[1].sort_values(ascending=False)[1:6]

UserID
5343    0.405356
5190    0.404446
1481    0.380623
1283    0.379054
5705    0.346293
Name: 1, dtype: float64

In [9]:
import seaborn as sns

In [10]:
tips = sns.load_dataset('tips')

In [11]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [12]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [14]:
# structured array로 부를 수 있음 / 문제점: dot notation으로 접근 불가능 따라서 record array로 사용
tips.set_index() # index를 다른것으로 바꿔서 보여줄 수 있다
# 이후 index sort가능
tips.set_index('sex').sort_index()
# 특정 값만 뽑고 싶으면 loc사용
tips.set_index('sex').sort_index().loc['Male']

array([10.34, 1.66, 'Male', 'No', 'Sun', 'Dinner', 3], dtype=object)

In [16]:
sim(3,3).index

Index([3000, 479, 5691], dtype='int64', name='UserID')

In [ ]:
rating[(rating.UserID==3000)|(rating.UserID==479)|(rating.UserID==5691)]
# boolean indexing으로 찾아오기

# or는 in으로 대체할 수 있다
a==3 or a==6
a in [3,6]

# 따라서, 이렇게 변경 가능하다
rating[rating.UserID in [3000, 479, 5691]]  # overloading이 keyword에 적용되지 않으므로 불가능
rating[rating.UserID.isin([3000, 479, 5691])]

In [17]:
rating = pd.read_csv('../19th day/ml-1m/ratings.dat', sep='::', header=None, names=['UserID','MovieID', 'Rating','Timestamp'])

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_46900\3163660120.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  rating = pd.read_csv('../19th day/ml-1m/ratings.dat', sep='::', header=None, names=['UserID','MovieID', 'Rating','Timestamp'])


In [40]:
movie = pd.read_csv('../19th day/ml-1m/movies.dat', sep='::', header=None, names=['MovieID','Title','Genres'], encoding='latin1')

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_46900\780918132.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movie = pd.read_csv('../19th day/ml-1m/movies.dat', sep='::', header=None, names=['MovieID','Title','Genres'], encoding='latin1')


In [42]:
def sim_movie(user_id, n=6):
    index = data[user_id].sort_values(ascending=False)[1:n+1].index
    movie_ = rating[(rating.UserID.isin(index))&(rating.Rating==5)]['MovieID'].values
    movie_id = np.unique(movie_)
    return movie[movie.MovieID.isin(movie_id)]

In [33]:
import numpy as np

In [34]:
np.unique(sim_movie(3)) # 중복 거르기
np.unique([1,2,2,2,1,1,1,2,1], return_counts=True)  # value count 해서 알려줌

array([   1,   10,   11,   32,   34,  110,  144,  150,  153,  161,  260,
        318,  339,  349,  362,  380,  440,  457,  480,  527,  553,  588,
        589,  590,  592,  593,  597,  648,  733,  858,  919,  934, 1015,
       1017, 1019, 1028, 1036, 1073, 1097, 1127, 1136, 1193, 1196, 1197,
       1198, 1199, 1201, 1210, 1221, 1222, 1234, 1240, 1246, 1254, 1259,
       1262, 1265, 1266, 1270, 1272, 1275, 1278, 1291, 1294, 1304, 1307,
       1356, 1373, 1376, 1387, 1569, 1580, 1610, 1653, 1663, 1704, 1747,
       1779, 1953, 1954, 1968, 2000, 2054, 2078, 2080, 2081, 2115, 2194,
       2302, 2355, 2470, 2571, 2615, 2640, 2716, 2797, 2858, 2871, 2872,
       2915, 2944, 2951, 2968, 3037, 3039, 3040, 3098, 3114, 3168, 3244,
       3358, 3360, 3361, 3408, 3421, 3479, 3494, 3501, 3526, 3552, 3578,
       3671, 3948], dtype=int64)

In [37]:
np.histogram([1,2,1,2,1,1,1], bins=3)   # bins는 몇등분할지 정해주는 것

(array([5, 0, 2], dtype=int64),
 array([1.        , 1.33333333, 1.66666667, 2.        ]))

In [43]:
sim_movie(3)

MovieID                           Title                       Genres
0           1                Toy Story (1995)  Animation|Children's|Comedy
9          10                GoldenEye (1995)    Action|Adventure|Thriller
10         11  American President, The (1995)         Comedy|Drama|Romance
31         32           Twelve Monkeys (1995)                 Drama|Sci-Fi
33         34                     Babe (1995)      Children's|Comedy|Drama
...       ...                             ...                          ...
3457     3526               Parenthood (1989)                 Comedy|Drama
3483     3552               Caddyshack (1980)                       Comedy
3509     3578                Gladiator (2000)                 Action|Drama
3602     3671          Blazing Saddles (1974)               Comedy|Western
3878     3948         Meet the Parents (2000)                       Comedy

[123 rows x 3 columns]

In [ ]:
# 문제가 경제적 공익적 학문적 가치가 있으면 있을수록 더 높은 점수를 받을 가능성이 존재한다
# 문제도 클수록 좋은 점수를 받는다
# 설득의 영역은 우리한테 맡겨진다
# 