In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
a.dtype

dtype('int32')

In [5]:
# description
class A:
    __x = 1

In [6]:
encapsulation (접근제한 거는 것)
특히 ,mangling이라고 함

['_A__x',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [18]:
class B:
    def __get__(self, a, b):
        print('get')
    def __set__(self, x):
        print('set')
        return 1

class C:
    bb = B()
    def __init__(self):
        self.b = B()

In [12]:
        
C.bb = 3

In [14]:
C.bb

3

In [24]:
cc= C()

In [ ]:
cc.bb

In [26]:
class B:
    def __get__(self, a, b):
        print('get')
    def __set__(self, x, y):
        print('set')
        return 1

class C:
    bb = B()
    def __init__(self):
        self.b = B()

In [27]:
dd = C()

In [28]:
dd.bb

get


In [29]:
dd.bb = 3

set


In [30]:
dd.bb

get


In [32]:
a = np.array([1,2,3,4])

In [33]:
a.shape = (2,2)

In [34]:
a

array([[1, 2],
       [3, 4]])

In [7]:
class D:
    def __init__(self):
        self.__x = 0

    def g(self):
        print('get')
        return self.__x    

    def s(self, t):
        print('set')
        self.__x = t+1

    x = property(g, s)

In [8]:
d = D()

In [9]:
d.x = 5

set


In [10]:
d.x

get


6

In [45]:
class E:
    def __init__(self, x):
        self.__xx = x
    
    @property
    def t(self):
        return self._E__xx
    
    @t.setter
    def t(self, x):
        print('set')
        self.__xx = x

In [46]:
d = E(3)

In [50]:
d.t

5

In [48]:
d.t = 5

set


In [52]:
import numpy as np

a = np.array([1,2,3,4])

In [53]:
a.ndim = 2
# 안되게 만들어놓음

AttributeError: attribute 'ndim' of 'numpy.ndarray' objects is not writable

In [54]:
a = np.zeros((3,4))

In [65]:
a = np.identity(4)
a
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
np.triu((3,4))
np.tril((3,4))

array([[3, 0],
       [3, 4]])

In [67]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [68]:
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
np.lookfor('triangle')
np.info('tril')

Search results for 'triangle'
-----------------------------
numpy.tril
    Lower triangle of an array.
numpy.triu
    Upper triangle of an array.
numpy.hypot
    Given the "legs" of a right triangle, return its hypotenuse.
numpy.tril_indices
    Return the indices for the lower-triangle of an (n, m) array.
numpy.triu_indices
    Return the indices for the upper-triangle of an (n, m) array.
numpy.ma.hypot
    Given the "legs" of a right triangle, return its hypotenuse.
numpy.tril_indices_from
    Return the indices for the lower-triangle of arr.
numpy.triu_indices_from
    Return the indices for the upper-triangle of arr.
numpy.linalg._umath_linalg.eigh_lo
    eigh on the last two dimension and broadcast to the rest, using lower triangle
numpy.linalg._umath_linalg.eigh_up
    eigh on the last two dimension and broadcast to the rest, using upper triangle.
numpy.sin
    Trigonometric sine, element-wise.
numpy.tri
    An array with ones at and below the given diagonal and zeros elsewhere.


In [75]:
class A:
    def __str__(self):
        print('str')
        return '1'
    def __repr__(self):
        print('repr')
        return '2'

In [76]:
x = A()

In [77]:
A()

repr


2

In [78]:
print(x)

str
1


In [79]:
a = np.array([1,2,3,4])

In [80]:
a

array([1, 2, 3, 4])

In [81]:
print(a)

[1 2 3 4]


In [82]:
aa =np.array([[1,2],[3,4]])
bb = np.array([[1,2],[3,4]])

In [83]:
aa*bb

array([[ 1,  4],
       [ 9, 16]])

In [84]:
# indexing slicing
# 5가지
a = np.arange(24).reshape(4,6)

In [85]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [86]:
a[0,2]

2

In [88]:
b = np.array([1,2,3,4])
b[b>2].max()

4