In [1]:
import numpy as np

In [17]:
a = np.array([5,8,7,1,2,10])
b = np.array([7,29,10,5,3])

In [3]:
np.savez('saved.npz', array1 = a, array2 = b)

In [4]:
data = np.load('saved.npz')

In [25]:
t3 = np.sort(data, axis=0)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [16]:
a.sort()
print(a)
type(a)


[ 1  2  5  7  8 10]


numpy.ndarray

In [28]:
array = np.array([[5,9,10,3,1],[8,4,3,2,5],[9,2,7,1,4]])
array.sort(axis=1)
print(array)

[[ 1  3  5  9 10]
 [ 2  3  4  5  8]
 [ 1  2  4  7  9]]


In [34]:
array = np.linspace(0, 10, 5, axis=0)
print(array)
print(array[1])

[ 0.   2.5  5.   7.5 10. ]
2.5


In [50]:
a = np.random.seed(0)
# 난수 생성기
print(np.random.rand(7))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721]


In [52]:
b = array.copy()

In [64]:
hex(b.__array_interface__['data'][0])

'0x1192e4de9b0'

In [65]:
hex(array.__array_interface__['data'][0])

'0x1192e4de950'

In [70]:
array2 = np.random.randint(0, 10, 10)
print(array2)
print(hex(array2.__array_interface__['data'][0]))

[0 3 5 0 2 3 8 1 3 3]
0x1192e4de860
